name: Időzítés teszt

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Automatikus indítás ellenőrzése
        run: |
          echo "Az időzített workflow elindult."
          date -u
